<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
      <Authors>wtfblub</Authors>
      <PackageId>BlubLib.DotNetty.SimpleRmi</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetty.Common" Version="0.4.6" />
    <PackageReference Include="DotNetty.Transport" Version="0.4.6" />
    <PackageReference Include="Sigil" Version="4.7.0" />
    <PackageReference Include="System.Reflection" Version="4.3.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlubLib.DotNetty\BlubLib.DotNetty.csproj" />
    <ProjectReference Include="..\BlubLib.Serialization\BlubLib.Serialization.csproj" />
  </ItemGroup>
    <Import Project="..\version.targets"/>
</Project>
